name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"   # roda 1x por dia
  workflow_dispatch:       # permite rodar manualmente também

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
