name: Generate Snake

on:
  schedule: # roda todo dia à meia-noite
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: anagudez
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit e push da cobrinha
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
